repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: debug-statements
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-json
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: no-commit-to-branch
        always_run: false
        exclude: fragments\/.*|(?x)^(CHANGELOG.md|pyproject.toml|sonar-project.properties)$
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: safety-check
        name: Safety-DB Check
        entry: poetry run safety
        args: [check]
        language: system
        verbose: false
        pass_filenames: false

      - id: check-datetime-now
        name: check_datetime_now
        description: Prefer datetime.utcnow()
        language: pygrep
        entry: 'datetime\.now\(\)'
        types: [python]

      - id: check-poetry
        name: Poetry check
        description: Validates the structure of the pyproject.toml file
        entry: poetry check
        language: system
        pass_filenames: false
        files: pyproject.toml

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ["--exclude=docs/*,*migrations*", "--ignore=E501,W503,E203"]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--check-only", "--diff"]
        additional_dependencies: ["toml"]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-mock-methods

  - repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
      - id: black
